name: test
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: golang
    steps:
      - uses: actions/checkout@v2
      - run: go build
      - run: go run github.com/golangci/golangci-lint/cmd/golangci-lint run
      - run: go test -covermode atomic -coverprofile coverage.txt
      - uses: codecov/codecov-action@v1
      - run: go test -bench .
